/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

import java.io.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author USER
 */
public class KasirForm extends javax.swing.JFrame {

    String tujuan,temp = "";
    Integer totalbelanja = 0,hargabelanja,kembalian,j;
    String[] nama,harga,stok;
    
    /**
     * Creates new form KasirForm
     */
    public KasirForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUtama = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        txtJumlahBarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTotalBelanja = new javax.swing.JTextField();
        txtUangBayar = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JButton();
        btnMakanan = new javax.swing.JToggleButton();
        btnMinuman = new javax.swing.JToggleButton();
        btnMandi = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUtama.setText("Menu Utama");
        btnUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtamaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Kasir");

        jLabel1.setText("ID Barang");

        jLabel2.setText("Jumlah Barang");

        jLabel3.setText("Jenis Barang");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jLabel4.setText("Id,Jenis,Nama,Harga,Jumlah,Total Harga");

        jLabel5.setText("Total Belanja");

        jLabel7.setText("Uang Bayar");

        jLabel8.setText("Kembalian");

        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnMakanan.setText("Makanan");
        btnMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakananActionPerformed(evt);
            }
        });

        btnMinuman.setText("Minuman");
        btnMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinumanActionPerformed(evt);
            }
        });

        btnMandi.setText("Mandi");
        btnMandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMandiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnUtama)
                .addGap(203, 203, 203)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btnMakanan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMandi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMinuman))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTransaksi))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMakanan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinuman)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMandi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtamaActionPerformed
        PenggunaForm x = new PenggunaForm();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUtamaActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        try
        {
            if (Integer.parseInt(txtUangBayar.getText())<totalbelanja)
                {
                    JOptionPane.showMessageDialog(rootPane,"Uang Tidak Cukup");
                }
            else
            {
                kembalian = Integer.parseInt(txtUangBayar.getText())-totalbelanja;
                txtKembalian.setText(Integer.toString(kembalian));
                FileWriter fw = new FileWriter ("src/Data_Transaksi.txt",true);
                fw.write(temp);
                fw.write("Total Belanja : Rp."+Integer.toString(totalbelanja)+"\n");
                fw.write("Uang Bayar : Rp."+txtUangBayar.getText()+"\n");
                fw.write("Kembalian : Rp."+Integer.toString(kembalian)+"\n");
                fw.write("\n");
                fw.close();
                JOptionPane.showMessageDialog(rootPane,"Berhasil\nData Tersimpan");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"ERROR");
        }
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakananActionPerformed
        try
        {
            File Array = new File("src/Data_Makanan.txt");
            Scanner baca = new Scanner(Array);
            ArrayList<String> note = new ArrayList<>();
            while (baca.hasNextLine())
            {
                note.add(baca.nextLine());
            }

            nama = ((note.get(Integer.parseInt(txtIdBarang.getText())*7-(7-1))).split(" : "));
            harga = ((note.get(Integer.parseInt(txtIdBarang.getText())*7-(7-2))).split("Rp."));
            stok = ((note.get(Integer.parseInt(txtIdBarang.getText())*7-(7-3))).split(" : "));

            hargabelanja = (Integer.parseInt(harga[1])*Integer.parseInt(txtJumlahBarang.getText()));
            temp = temp+txtIdBarang.getText()+","+"Makanan"+","+nama[1]+","+harga[1]+","+txtJumlahBarang.getText()+","+Integer.toString(hargabelanja)+"\n";
            txtArea.setText(temp);
            totalbelanja = totalbelanja+hargabelanja;
            txtTotalBelanja.setText(Integer.toString(totalbelanja));
            
            if (!note.isEmpty())
            {
                PrintWriter pw = new PrintWriter("src/Data_Makanan.txt");
                for (int i = 0; i < note.size();i++)
                {
                    if (i == ((Integer.parseInt(txtIdBarang.getText()))*7-(7-3)))
                    {
                        String[] temp;
                        temp = ((note.get(i)).split(" : "));
                        pw.println("Stok : "+(Integer.parseInt(temp[1])-(Integer.parseInt(txtJumlahBarang.getText()))));
                    }
                    else
                    {
                        pw.println(note.get(i));
                    }
                }
                pw.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"ERROR");
        }
    }//GEN-LAST:event_btnMakananActionPerformed

    private void btnMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinumanActionPerformed
        try
        {
            File Array = new File("src/Data_Minuman.txt");
            Scanner baca = new Scanner(Array);
            ArrayList<String> note = new ArrayList<>();
            while (baca.hasNextLine())
            {
                note.add(baca.nextLine());
            }

            nama = ((note.get(Integer.parseInt(txtIdBarang.getText())*7-(7-1))).split(" : "));
            harga = ((note.get(Integer.parseInt(txtIdBarang.getText())*7-(7-2))).split("Rp."));
            stok = ((note.get(Integer.parseInt(txtIdBarang.getText())*7-(7-3))).split(" : "));

            hargabelanja = (Integer.parseInt(harga[1])*Integer.parseInt(txtJumlahBarang.getText()));
            temp = temp+txtIdBarang.getText()+","+"Minuman"+","+nama[1]+","+harga[1]+","+txtJumlahBarang.getText()+","+Integer.toString(hargabelanja)+"\n";
            txtArea.setText(temp);
            totalbelanja = totalbelanja+hargabelanja;
            txtTotalBelanja.setText(Integer.toString(totalbelanja));
            
            if (!note.isEmpty())
            {
                PrintWriter pw = new PrintWriter("src/Data_Minuman.txt");
                for (int i = 0; i < note.size();i++)
                {
                    if (i == ((Integer.parseInt(txtIdBarang.getText()))*7-(7-3)))
                    {
                        String[] temp;
                        temp = ((note.get(i)).split(" : "));
                        pw.println("Stok : "+(Integer.parseInt(temp[1])-(Integer.parseInt(txtJumlahBarang.getText()))));
                    }
                    else
                    {
                        pw.println(note.get(i));
                    }
                }
                pw.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"ERROR");
        }
    }//GEN-LAST:event_btnMinumanActionPerformed

    private void btnMandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMandiActionPerformed
        try
        {
            File Array = new File("src/Data_PerlengkapanMandi.txt");
            Scanner baca = new Scanner(Array);
            ArrayList<String> note = new ArrayList<>();
            while (baca.hasNextLine())
            {
                note.add(baca.nextLine());
            }

            nama = ((note.get(Integer.parseInt(txtIdBarang.getText())*6-(6-1))).split(" : "));
            harga = ((note.get(Integer.parseInt(txtIdBarang.getText())*6-(6-2))).split("Rp."));
            stok = ((note.get(Integer.parseInt(txtIdBarang.getText())*6-(6-3))).split(" : "));

            hargabelanja = (Integer.parseInt(harga[1])*Integer.parseInt(txtJumlahBarang.getText()));
            temp = temp+txtIdBarang.getText()+","+"Perlengkapan Mandi"+","+nama[1]+","+harga[1]+","+txtJumlahBarang.getText()+","+Integer.toString(hargabelanja)+"\n";
            txtArea.setText(temp);
            totalbelanja = totalbelanja+hargabelanja;
            txtTotalBelanja.setText(Integer.toString(totalbelanja));
            
            if (!note.isEmpty())
            {
                PrintWriter pw = new PrintWriter("src/Data_PerlengkapanMandi.txt");
                for (int i = 0; i < note.size();i++)
                {
                    if (i == ((Integer.parseInt(txtIdBarang.getText()))*6-(6-3)))
                    {
                        String[] temp;
                        temp = ((note.get(i)).split(" : "));
                        pw.println("Stok : "+(Integer.parseInt(temp[1])-(Integer.parseInt(txtJumlahBarang.getText()))));
                    }
                    else
                    {
                        pw.println(note.get(i));
                    }
                }
                pw.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"ERROR");
        }
    }//GEN-LAST:event_btnMandiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnMakanan;
    private javax.swing.JToggleButton btnMandi;
    private javax.swing.JToggleButton btnMinuman;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtJumlahBarang;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtTotalBelanja;
    private javax.swing.JTextField txtUangBayar;
    // End of variables declaration//GEN-END:variables
}
